### ISSUE TITLE
[BUG]  Focus abnormality

### ISSUE THREAD

**Issue by oeyoews** [TiddlyWiki/TiddlyWiki5#7798]
### Describe the bug

when set autofocus to text, if input on type field, this focus alway focus on editor 

### To Reproduce

1. Go to [tiddlywiki autofocus](https://tiddlywiki.com/#%24%3A%2Fconfig%2FAutoFocus)
2. change title to text
3. create new tiddler, and input on type field
4. this focus alway focus the editor on typing

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
- Plugins installed [e.g. Freelinks, TiddlyMap]

**Comment by pmario** [comment]
IMO related to:  [IDEA] it is proposed to add a "focusSelect" parameter to the edit-text widget #7221 
and: Add focusSelect attribute to <$edit-text> widget #7222 

Check those issues and the related Talk threads. May be there is something useful.

**Comment by Jermolene** [comment]
Thank you @oeyoews.

It occurs to me that this behaviour may be intentional - @BurningTreeC would you kindly be able to investigate?

**Comment by pmario** [comment]
I did just replicate the problem. If I want to write a custom text into the type field, the focus jumps after typing the first character. If the type is selected again. The focus does not jump anymore. 

So if an existing element from the dropdown is selected, it may be intentional. 

But if the user wants to manually input a type-info, jumping after the first character seems to be a bug.

**Comment by BurningTreeC** [comment]
I'll investigate

**Comment by Jermolene** [comment]
Thank you @pmario @BurningTreeC much appreciated.

**Comment by BurningTreeC** [comment]
Ok, the editor re-renders and sets auto-focus when it's expected
But it's confusing behavior
The intended behavior is to set auto-focus when the tiddler is opened for editing
I think we can do something here

**Comment by BurningTreeC** [comment]
I've created a Draft PR that addesses this issue: #7800

**Comment by BurningTreeC** [comment]
Let's name the problem, to understand it better.
The editor type changes and the editor gets redrawn and gets focus because of that redraw.
That steals the focus of the type input field.
We need a little mechanism to tell if an element has focus which should not get "stolen".
Maybe we add the class `tc-keep-focus` to the type input field and test in factory.js if the activeElement has that class.

**Comment by BurningTreeC** [comment]
I've now added PR #7805 that should fix the issue correctly

**Comment by oeyoews** [comment]
Is there any progress on this issue now?

For textarea type editors, all text will be automatically selected (which really affects the editing experience), which also explains why this problem occurs when switching text types.

![Screenity video - Jan 26, 2024 (1)](https://github.com/Jermolene/TiddlyWiki5/assets/72405338/34e0ac7f-1063-437b-b5df-2ae1da43385d)

**Comment by Jermolene** [comment]
Hi @oeyoews I don't think @BurningTreeC has been available since we found the issues with #7805.

**Comment by pmario** [comment]
@Jermolene -- I did just test this issue with v5.3.7 and there seems to be **no problem** anymore. IMO this one can be closed

**Comment by saqimtiaz** [comment]
@pmario the issue still seems to be present. Try switching the type from none to text/plain, the focus jumps to the text field and the entire text is selected.

The same thing happens when you edit a tiddler with $:/config/AutoFocus set to text

**Comment by pmario** [comment]
@saqimtiaz .. The issue in the OP is different to the animated GIF. 

The issue in the GIF IMO is expected. If we set the cursor to the beginning of the tiddler, we will immediately get an issue that users want it at the end and vice versa. Or they want the cursor to be when the tiddler was saved. .. 

I did test it, to put the cursor at the beginning of the text. There are 2 problems:

- The blinking cursor is almost invisible, even if it blinks
- After several seconds the cursor stops blinking (tested with FF lately and Edge a year ago or so)
  - Probably a problem with iframes

**Comment by BurningTreeC** [comment]
Hi @pmario @saqimtiaz @oeyoews  @Jermolene ... my PR is now building ... the test environment had to be tricked with a `$tw.browser` check

**Comment by pmario** [comment]
PR has been merged
